--- #YAML:1.0
name:               Net-Domain-Regex
version:            0.001006
abstract:           Class to extract domain names from text
author:
    - Peter Blair (pblair@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  6.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
